version: '3.8'
services:
  stats-server:
    build: ./statistics
    container_name: EWM-Stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/EWM_statistics
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: EWM-DB-Stats
    ports:
      - "6542:5432"
    volumes:
      - /EWM_stats-postgresql-db
    environment:
      - POSTGRES_DB=EWM_statistics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./server
    container_name: EWM-Server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - TZ="Europe/Moscow"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/EWM_server
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - STAT-SERVER-URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: EWM-DB-Server
    ports:
      - "6541:5432"
    volumes:
      - /EWM_service-postgresql-db
    environment:
      - POSTGRES_DB=EWM_server
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
